-- ThantFlash schema. Works on both H2 and PostgreSQL.

create table app_user (
    id            bigint generated by default as identity primary key,
    username      varchar(50)  not null unique,
    password_hash varchar(100) not null,
    created_at    timestamp with time zone not null
);

create table deck (
    id         bigint generated by default as identity primary key,
    user_id    bigint       not null references app_user (id) on delete cascade,
    name       varchar(100) not null,
    created_at timestamp with time zone not null,
    constraint uq_deck_user_name unique (user_id, name)
);

create table card (
    id            bigint generated by default as identity primary key,
    deck_id       bigint        not null references deck (id) on delete cascade,
    front         varchar(2000) not null,
    back          varchar(2000) not null,
    interval_days double precision not null,
    ease          double precision not null,
    due_at        timestamp with time zone not null,
    reps          integer       not null,
    created_at    timestamp with time zone not null
);
create index idx_card_deck_due on card (deck_id, due_at);

-- One row per answer; used for statistics.
create table review_log (
    id          bigint generated by default as identity primary key,
    card_id     bigint      not null references card (id) on delete cascade,
    user_id     bigint      not null references app_user (id) on delete cascade,
    grade       varchar(10) not null,
    reviewed_at timestamp with time zone not null
);
create index idx_review_user_time on review_log (user_id, reviewed_at);
